cmd: "stack build && echo \"\n\n\" && ./scheme48 \"'#(a '(quoted (dotted . list)) \\\"string with \\\\\\\"quoted\\\\\\\" string\\\" #t #f test)\""

#cwd: "{PROJECT_PATH}/grains"
errorMatch:
  - ' *(?<file>.+\.l?hs):(?<line>\d+):(?<col>\d+):'
  - '### Failure in: (?<name>.*)\n(?<file>.+\.l?hs):(?<line>\d+)\n(?<message>expected.*\n but got.*)'
